# Generated by Django 3.0.4 on 2020-04-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200402_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Read_number',
        ),
    ]
