# Generated by Django 3.0.4 on 2020-05-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200504_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_time']},
        ),
    ]
